### ISSUE TITLE
Adding a footer and integrating the social links in that

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#13]
<h2 align="center">Issue picture</h2>
<div align="center">
<p> Adding a footer and integrating the social links in that (including all general things a footer has) </p>
<img src="https://cdn.discordapp.com/attachments/802260112252731433/889773255899086868/unknown.png" height="150px" width="550px"> <br><br>
<img src="https://cdn.discordapp.com/attachments/802260112252731433/889773894817419324/bgAAAABJRU5ErkJggg.png" height="150px" width="550px">
<p>You may use the following link for your reference:</p>
<a href="https://www.w3schools.com/tags/tag_footer.asp"> https://www.w3schools.com/tags/tag_footer.asp </a> </p><br>
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>
</div>

**Comment by Divyateja04** [comment]
Um hey, I would like to work on this so can you assign this to me. Also is it okay if I submit my PR in october though so that it counts for hacktoberfest
Also I have knowldge about web dev but honestly no idea about flask so can you give me any starting points on how to find the html files and add the code

**Comment by Divyateja04** [comment]
Also um why is bootstrap not linked into this project, the head had some comment but I couldn't understand..most footers might use bootstrap containers and that wouldn't work right?

**Comment by Divyateja04** [comment]
I went through it and added some code to home.html and got to this.
![image](https://user-images.githubusercontent.com/28446977/134143344-80b14705-4f2e-4748-bd20-79eb82d73e94.png)
Tell me how it looks and any other changes to do

**Comment by pulkithanda** [comment]
Great! Thank you, Assigned the issue to you ^_^. Yeah, you can submit it in October so that it gets counted in hacktoberfest. About the Flask files, I think you have figured it out seeing the screenshot? If not then contact me on my discord (Alphabet# 0352) I'll give you a brief walkthrough. Also, The footer is perfect! No changes are needed. Just try to make it responsive nothing else.

**Comment by Divyateja04** [comment]
Sure I'll try to make it as responsive as possible

**Comment by Divyateja04** [comment]
Also I had noticed that, when you click on signin/register the form we get overlaps the navbar completely so can I work on that too....honestly can't promise anything here but wanted to let you know this is an issue too

**Comment by pulkithanda** [comment]
Didn't get what you're referring to can you maybe attack a clip of the same or dm on discord, thanks

**Comment by pulkithanda** [comment]
Thank you for contributing ^_^
