### ISSUE TITLE
Improvement of the responsiveness of the login form

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#18]
<h2 align="center">Issue picture</h2>
<div align="center">
<p> Making the login form responsive </p>
<img src="https://cdn.discordapp.com/attachments/791743706402652170/891040235620827136/unknown.png" height="300px">
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>
</div>

**Comment by Divyateja04** [comment]
Hey I would like to work on this, can you assign this to me?

**Comment by pulkithanda** [comment]
Hey there! Sure go ahead, Assigned the issue to you

**Comment by pulkithanda** [comment]
Thank you for your contributions ^_^
