### ISSUE TITLE
Hosting the site on Heroku/ Replit

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#23]
<h2 align="center"> Hosting this flask site on Heroku/ Replit </h2>
<div align="center">
<p> Making the necessary changes so it is easy to host the site on heroku / replit. Also include a document on how to host a local copy of the forks to make it easier for the people forking the repository. </p>
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>

**Comment by saif-malik-01** [comment]
@pulkithanda can you please elaborate. You want this site to be deploy on heroku ?

**Comment by pulkithanda** [comment]
@saif-malik-01 Yes this one

**Comment by saif-malik-01** [comment]
we can include a Hosting section in the read-me file for that ? and I deploy this one on my heroku id ?

**Comment by pulkithanda** [comment]
Yeah in the readme it would be great. yeah you can deploy and make changes for dit to be deployed I'll accept the PR

**Comment by saif-malik-01** [comment]
please assign this to me, then I start work on it.

**Comment by pulkithanda** [comment]
Sure go ahead, Assigned the issue to you

**Comment by saif-malik-01** [comment]
I successfully deployed the website you can check it at https://voyager-space.herokuapp.com/
After finalizing the readme and deployment I will make a pr soon.

**Comment by pulkithanda** [comment]
yea it works, go ahead

**Comment by saif-malik-01** [comment]
@pulkithanda can you please review and merge the pr #24 Which fix the error in the code.

**Comment by pulkithanda** [comment]
@saif-malik-01 I have posted a comment there do check it

**Comment by pulkithanda** [comment]
Thank you for contributing ^_^
