### ISSUE TITLE
Rectifying the see responses form

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#42]
<h2 align="center">Rectifying the see responses form </h2>
<div align="center">
<p> Rectifying the see responses form so that its design is like the login / register form some bug has caused this</p>
<img src="https://cdn.discordapp.com/attachments/789454958453063702/894096901442510908/unknown.png" height="300px">
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>

**Comment by gamer-1478** [comment]
could you assign it to me?

**Comment by pulkithanda** [comment]
Hey there! Sure go ahead
