### ISSUE TITLE
Adding a search box facility in the navbar

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#47]
<h2 align="center">Adding a search box facility in the navbar </h2>
<div align="center">
<p> Adding a search menu option in the navbar with search functionality </p>
<img src="https://cdn.discordapp.com/attachments/789454958453063702/894100503963770920/unknown.png">
<p>You may use the following links for your reference:</p>
<p><a href="https://www.youtube.com/watch?v=v1PeTDrw6OY">https://www.youtube.com/watch?v=v1PeTDrw6OY </a><br>
<a href="https://codepen.io/ShortCode/pen/jOrBeOw"> https://codepen.io/ShortCode/pen/jOrBeOw</a> </p><br>
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>

**Comment by JanviRaina** [comment]
I would like to work on this.

**Comment by pulkithanda** [comment]
Hey there @JanviRaina Sure go ahead! Assigned it to you ^_^

**Comment by vampnik** [comment]
Can I also contribute to this issue.

**Comment by pulkithanda** [comment]
Sure @vampnik Go ahead
