### ISSUE TITLE
Adding a contact us form 

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#48]
<h2 align="center"> Adding a contact us form  </h2>
<div align="center">
<p> Adding a contact us form which should be visible with / without login in the navbar </p>
<p> The contact form should match with the theme and be responsive </p>
<p>You may use the following links for your reference:</p>
<p><a href="https://www.youtube.com/watch?v=l_Z3N3etkS0">https://www.youtube.com/watch?v=l_Z3N3etkS0</a><br><br>
<img src="https://cdn.discordapp.com/attachments/891968146024562720/894088785346854912/unknown.png" height="250">

<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>

**Comment by Harsh-Singh-Rajput** [comment]
hello @pulkithanda can i start making contact form
?

**Comment by pulkithanda** [comment]
Hey there @Harsh-Singh-Rajput Sure go ahead mate! Do keep in mind it should be visible both before and after logging in.
Make a navbar place for contact too after the procedure where you can add it

**Comment by Harsh-Singh-Rajput** [comment]
@pulkithanda  you mean navbar in contact form  ?

**Comment by pulkithanda** [comment]
Adding a contact element in the navbar like there's one for login register

**Comment by Harsh-Singh-Rajput** [comment]
@pulkithanda ok got it thanks for assigning it to me

**Comment by pulkithanda** [comment]
Happy Hacktoberfest ^_^

**Comment by Harsh-Singh-Rajput** [comment]
please also tell me what details you want to be filled by user in form

**Comment by Harsh-Singh-Rajput** [comment]
hello @pulkithanda how should i run and check the page locally because  the page is not applying css

**Comment by pulkithanda** [comment]
Its a flask website. First of all you should be familiar with how to run a flask website. Use the run.py file and copy the local host generated and paste it on the web. Insert the components correctly so as to not mess up with the backend. For any other problems, you can contact me on discord. You can view how I have made the login form and functionality for reference.

**Comment by Harsh-Singh-Rajput** [comment]
ok

**Comment by Harsh-Singh-Rajput** [comment]
![image](https://user-images.githubusercontent.com/61553586/135751350-d7a706a8-a287-439c-b7a7-95e416140a46.png)
@pulkithanda i made the contact page by reusing main.css theme so that it matches with site , pls see this whether it is ready for pr or should I have to make changes.
And also I didn't know python backend that's why I was unable to link it with database sorry for that

**Comment by Harsh-Singh-Rajput** [comment]
will you tell me how to link it with database?

**Comment by akgupta0777** [comment]
I came here to take this issue but it's already assigned.
@Harsh-Singh-Rajput By the way nice work.

**Comment by Harsh-Singh-Rajput** [comment]
> I came here to take this issue but it's already assigned. @Harsh-Singh-Rajput By the way nice work.

Thanks for appreciation, yes this is assigned to me😃

**Comment by pulkithanda** [comment]
@Harsh-Singh-Rajput I wanted you to make it different from the other forms like using some svgs etc. Anyways leave some spaces and match the spacings if you're making them like others. Also as for the database, I have used flask so maybe try to link it then it's nice. I'll merge after that. You can dm on discord if any problems. Also @akgupta0777 you can contribute too I can mark your PR as hacktoberfest-accepted and then it will count so up to you. An issue can have multiple assignees.

**Comment by akgupta0777** [comment]
@pulkithanda what do you want to do in the backend once the send button is clicked on the contact page.

**Comment by pulkithanda** [comment]
The contact responses are stored in a local database or sent to a google doc whichever? like the admin panel responses. Also checks on the fields of contact forms like login and register forms.
