### ISSUE TITLE
Styling the alerts to make them readable

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#5]
<h2 align="center">Issue picture</h2>
<div align="center">
<p> Styling these alerts (eg the username is taken pls choose a different one) to make them more presentable (You're allowed to use bootstrap as long as it doesn't spoil the other parts of the website). Maybe displaying them at the top of the page or below or using any style you want. Also make sure that the alignment and the orientation of the form doesn't get spoiled.</p>
<img src="https://cdn.discordapp.com/attachments/798877499038760981/887688051118207007/unknown.png">
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>
</div>

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue

**Comment by pulkithanda** [comment]
Hey there! Sure go ahead, Thank you 
Assigned the issue to you

**Comment by pulkithanda** [comment]
@himanshu007-creator I see you have submitted the PR now but if I accept it, It won't be counted in hacktoberfest( If you're participating in that). Your PR will only be counted for hacktoberfest if you submit it in October. So do let me know below that should I merge it now or later in October. I'll check the work too. Thanks for contributing :D

**Comment by himanshu007-creator** [comment]
@pulkithanda  Thanks for your concern Bhai, but I think hacktoberfest can wait for now. Please review my PR today itself and if it's good, please merge!🎉

**Comment by pulkithanda** [comment]
@himanshu007-creator ohk sure bhai I'll just check and merge (btw if it helped you, please consider following would help me in further projects, thanks!)
